version: "{branch} {build}"

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

cache:
  - C:\Users\appveyor\.gradle\wrapper
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.m2

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'

    on_build_status_changed: true
    on_build_failure: true