name: Build and test
on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    strategy:
      matrix:
        gradle-version: [ '7.6.2', '8.0.1', '8.2.1' ]

    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}
          arguments: check --continue

#    TODO Add publish on tag support
