name: Build and test
on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    strategy:
      matrix:
        gradle-version: [ '7.6.2', '8.0.1', '8.2.1' ]

    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - run:
          ./gradlew check --continue
