name: Build and test
on: [ push, pull_request ]

jobs:
  ci:
    strategy:
      matrix:
        gradle-version: [ '7.6.4', '8.7', '8.12.1', 'current' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - run:
          ./gradlew check --continue
